# Generated by Django 5.2.4 on 2025-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
