# Generated by Django 5.2.4 on 2025-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Travel', 'Travel'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
    ]
