# Generated by Django 5.2.4 on 2025-08-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='title',
            new_name='description',
        ),
    ]
