# Generated by Django 5.2.4 on 2025-08-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
