# Generated by Django 5.2.4 on 2025-08-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
